### ISSUE TITLE
Find/Replace in files popup closed after switching focus

### ISSUE THREAD

**Issue by jwillebrands** [jwillebrands/ij-sloppy-focus#14]
> In release 0.5.0 on PhpStorm 2023.2.3, at least the 'Find in files' and 'Replace in files' popups will be closed when the editor receives focus, making it harder to use those dialogs.
> 
> Is that due to the same issue mentioned above, or is that a separate issue?

_Originally posted by @MrHaroldA in https://github.com/jwillebrands/ij-sloppy-focus/issues/1#issuecomment-1782644732_

**Comment by jwillebrands** [comment]
Thanks for your report MrHaroldA. I've spun it out to a separate issue because it may or may not be related. I can reproduce your issue without Sloppy Focus enabled, so it may not be caused by the plugin. Are you using sloppy focus in your desktop window manager as well? If so, could you confirm if the focus switch and subsequent close also happens with Sloppy Focus disabled?

I see this behavior on both my machines, one using i3, the other sway, both using the window manager's sloppy focus mode. When I move the mouse out of the find/replace dialog, the wm focuses the main IntelliJ window and closes the dialog.

**Comment by MrHaroldA** [comment]
I've set the Windows Focus to 'Click to Focus' in Gnome's Tweaks, but the dialogs are still closed when I move my cursor onto either the editor window, or an open terminal. Hovering over the Terminal title bar (or any other UI element) does not close the dialog, it closes as soon as the mouse cursor is in the editor or terminal.

**Comment by jwillebrands** [comment]
Alrighty, will take a look if there's an easy way to prevent that. I was able to reproduce it locally as well after disabling sloppy focus in i3. Thanks for the report!

**Comment by jwillebrands** [comment]
Sorry, took a while to find the time to look into this. The fix proved pretty straightforward though. Release is brewing up and will be submitted for Jetbrains approval. Should be ready by tomorrow. Thanks for your report!
