### ISSUE TITLE
Introduce a delay before switching focus

### ISSUE THREAD

**Issue by jwillebrands** [jwillebrands/ij-sloppy-focus#2]
With scroll-to-focus enabled, sloppy focus can be rather annoying when moving through a different editor to the project view. If the two files are not related, the project tree can scroll to a location nowhere near where you wanted to be.

**Comment by DavidAntliff** [comment]
I like this plugin but the first thing I noticed was the lag between the mouse moving to a new editor window and the focus switching - it's relatively slow and results in one or two characters being entered into the previous window before the focus shifts. It contributes to an overall "laggy" feel of the sloppy focus.

I see the delay is hard-coded to 200 ms. This is quite slow. Could the delay be customisable within the UI?

Also, can you elaborate on what "scroll-to-focus" is please, as I'd like to understand why the delay was added, and maybe experiment with a shorter delay myself.

**Comment by jwillebrands** [comment]
Heya David,

Glad you like the plugin. The delay has been configurable since version 0.2.0. You can find the setting in `Settings` > `Appearance & Bahvior` > `Sloppy Focus Settings`. Please let me know if that resolves the issue for you. If not, could you please open a new issue to track it?

As for scroll-to-focus: it's a feature of the project view. This has apparently been renamed (maybe for a long time already) to `Always select opened file`. It causes the project view to select whatever file currently has focus. I often have two editor windows side by side. The issue arose when I moved the cursor from the right editor window to the project view, thus passing over the left editor window. Without the delay, it would immediately select the left file in the project window, when I wanted to select a file close to the right file. The delay is to work around this behavior. Hope that makes sense.

**Comment by DavidAntliff** [comment]
Hi Jan-Willem, thank you for getting back to me. My apologies, you can indeed alter the delay. I am finding 50ms to be workable in my case - thank you.

"Always select opened file" - ah, I didn't know about that option, and yes I can see the issue when trying to get to the Project panel from the right-side panel. Having a longer delay makes perfect sense in this case. Thank you for explaining.

**Comment by jwillebrands** [comment]
No worries, glad to hear reducing the delay worked well for you. :)
