### ISSUE TITLE
Add switching between other types of tabs

### ISSUE THREAD

**Issue by skodnik** [jwillebrands/ij-sloppy-focus#3]
Add switching between other types of tabs (Project, Database, etc), not only split tabs (file tabs). 
Thank you! What I have been looking for for a long time!

**Comment by jwillebrands** [comment]
Heya, glad you like it! I was already playing around with some code to make it work for terminals, but can easily extend this to any focusable component. Will try to wrap this up over the weekend.

**Comment by jwillebrands** [comment]
Took a bit longer, but new version is being brewed up as we speak. I wanted to make it an option so if it somehow fails miserably, at least it can be switched off. You can find the setting in `Settings` > `Appearance and Behavior` >  `Sloppy Focus Settings`. 

It might be a little overzealous with focus switching, so please feel free to open a new issue if it's not working as you expected.

More configurable focus control will be coming up in a future release.
